project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    
website:
  title: "Reviews Climsci Trust Megastudy"
  navbar:
    left:
      - text: "Analysis"
        menu:
          - href: analysis.qmd
            text: "standardized scores"
          - href: analysis_non_standardized.qmd
            text: "non-standardized scores"
      - text: "Data Explorer"
        menu:
          - href: data_explorer_comparison.qmd
            text: "overview"        
          - href: data_explorer.qmd
            text: "standardized scores"
          - href: data_explorer_non_standardized.qmd
            text: "non-standardized scores"
      - href: slides.qmd
        text: "Slides plenary meeting"
      - href: index.qmd
        text: "Selection (preliminary)"

  page-footer: 
    background: light
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Jan Pf√§nder</span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>, 
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>

format:
  html:
    toc: true
    toc-depth: 3

execute:
  freeze: auto 
  echo: false
  warning: false
  message: false



